export const ALLOWED_TRANSITIONS = {
  NEW: ['AI_CALL_SCHEDULED', 'IN_FOLLOW_UP', 'ON_HOLD', 'CLOSED_LOST'],
  AI_CALL_SCHEDULED: ['AI_CALL_DONE_INTERESTED', 'AI_CALL_DONE_NOT_INTERESTED', 'ON_HOLD'],
  AI_CALL_DONE_INTERESTED: ['IN_FOLLOW_UP', 'DEMO_SCHEDULED', 'ON_HOLD'],
  AI_CALL_DONE_NOT_INTERESTED: ['CLOSED_LOST', 'ON_HOLD', 'NEW'],
  IN_FOLLOW_UP: ['DEMO_SCHEDULED', 'QUOTATION_SENT', 'NEGOTIATION', 'CLOSED_LOST', 'ON_HOLD'],
  DEMO_SCHEDULED: ['DEMO_DONE', 'IN_FOLLOW_UP', 'CLOSED_LOST', 'ON_HOLD'],
  DEMO_DONE: ['QUOTATION_SENT', 'IN_FOLLOW_UP', 'CLOSED_LOST', 'ON_HOLD'],
  QUOTATION_SENT: ['NEGOTIATION', 'CONVERTED_WON', 'CLOSED_LOST', 'ON_HOLD'],
  NEGOTIATION: ['CONVERTED_WON', 'QUOTATION_SENT', 'CLOSED_LOST', 'ON_HOLD'],
  CONVERTED_WON: ['ON_HOLD'],
  CLOSED_LOST: ['NEW', 'ON_HOLD'],
  ON_HOLD: ['NEW', 'IN_FOLLOW_UP', 'CLOSED_LOST'],
};

export function getAllowedNextStatuses(currentStatus) {
  return ALLOWED_TRANSITIONS[currentStatus] || [];
}
